name: Integration Tests

on: [push] 

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Run Docker Image
        run: |
          docker build -t fashion-api .  # Build from project root
          docker run -d -p 8000:8000 fashion-api  
      - name: Run Integration Tests
        run: pytest kognitive_src/tests/integration_tests.py  
      - name: Stop Docker Container  
        if: always()  
        run: docker stop $(docker ps -q -f name=fashion-api)